# Generated by Django 3.1.5 on 2021-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.TextField()),
                ('energy', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
