# Generated by Django 3.1.5 on 2021-03-22 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='date',
        ),
        migrations.AddField(
            model_name='sell',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sell',
            name='user',
            field=models.CharField(default=datetime.datetime(2021, 3, 22, 16, 41, 42, 781327, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
