# Generated by Django 3.1.5 on 2021-03-22 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210322_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('transection', models.TextField()),
                ('energy', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='sell',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
