# Generated by Django 3.1.5 on 2021-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210323_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpcConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('rpc_password', models.CharField(max_length=200)),
            ],
        ),
    ]
