# Generated by Django 3.2.4 on 2021-06-22 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210325_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='relay_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('partner_name', models.CharField(max_length=200)),
                ('relaynumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='walletTopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('money', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='partner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='ttlprice',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='txid',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpcconfig',
            name='permission',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='fname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='ttlprice',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.FloatField(),
        ),
    ]
