# Generated by Django 3.2.4 on 2021-06-24 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210622_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relay_number',
            old_name='relaynumber',
            new_name='relaynumber_p',
        ),
        migrations.AddField(
            model_name='relay_number',
            name='relaynumber_u',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpcconfig',
            name='port',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
