# Generated by Django 3.2.4 on 2021-06-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210624_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relay_number',
            old_name='relaynumber_p',
            new_name='relaynum_p',
        ),
        migrations.RenameField(
            model_name='relay_number',
            old_name='relaynumber_u',
            new_name='relaynum_u',
        ),
    ]
